[browser]
# Whether to send usage statistics to Streamlit.
#
# Default: true
gatherUsageStats = false

[logger]
# Level of logging for Streamlit's internal logger: "error", "warning", "info", or "debug".
# Default: "info"
level = "info"